---
- name: show run
  hosts: localhost
  gather_facts: true
  
  tasks:
    - name: show running-config
      ios_command:
        commands:
             - show version
        provider: "{{ cli }}"
      register: show run
    
    - name: msg
      debug:
          msg: "{{ show_run.stdout_lines }}"
